image: ros:melodic-robot

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

cache:
  paths:
    - ccache/

catkin lint:
  stage: build
  image: ros:melodic-ros-core
  before_script:
    - apt update >/dev/null 2>&1
    - apt install -y python-catkin-lint python-rosdep >/dev/null 2>&1
    - rosdep init >/dev/null && rosdep update >/dev/null
  script:
    - catkin_lint -W3 .

catkin_make:
  stage: build
  script:
    - catkin_make

catkin tools:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
