#!/usr/bin/env python3

from follow_waypoints import follow_waypoints
import rospy


if __name__ == '__main__':
    try:
        follow_waypoints.main()
    except rospy.ROSInterruptException:
        pass

